//package org.launchcode.fourohfourfound.finalproject.service;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Service;
//import jakarta.persistence.EntityManager;
//
//@Service
//public class CharacterService {
//
//    private final EntityManager entityManager;
//
//    @Autowired
//    public CharacterService(EntityManager entityManager) {
//        this.entityManager = entityManager;
//    }
//
//    public void clearCache() {
//        entityManager.clear();
//    }
//
//}